#!/bin/bash

# Change to script dir
cd "$(dirname "$0")"

# Check directory
dir=${PWD##*/}
if [ $dir == 'unix' ]; then
    cd ../..
fi

# Get build type
build_type=$1
if [ '$build_type' == '' ]; then
	echo "WARNING: Build type not specified. Setting to debug mode..."
	$build_type="debug"
fi

# Setup cmake
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=$build_type
cd ..

# Call make
exec make -C build
