#!/bin/bash

# Change to script dir
cd "$(dirname "$0")"

# Check directory
dir=${PWD##*/}
if [ $dir == 'unix' ]; then
    cd ../..
fi

# Get build type
$build_type=$1
IF "$build_type"=="" (
	echo "WARNING: Build type not specified. Setting to debug mode..."
	$build_type="debug"
)

# Setup cmake
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=$build_type
cd ..

# Call make
exec make -C build "$@"

