#!/bin/bash

# Change to script dir
cd "$(dirname "$0")"

# Check directory
dir=${PWD##*/}
if [ $dir == 'scripts' ]; then
    echo "In 'scripts' folder. Changing to parent directory..."
    cd ..
fi

# Find binary
./scripts/unix/find_binary "debug"

# If we found the binary...
if [ $? -eq 0 ]; then
    # Set environment variables
    . ./scripts/osx/set_env "debug"

    # Run gdb
    exec gdb ./build/bin/debug/midistar "$@"
fi

