#!/bin/bash

# Change to script dir
cd "$(dirname "$0")"

# Check directory
dir="${PWD##*/}"
if [[ $dir == 'debian' ]]; then
    cd ../..
fi

# Get args
if [[ $# != 1 ]]; then
    echo "Usage: create_package <binaries_path>"
    exit
fi
binaries_path=$1

# Find binary
midistar_dir="${PWD}"
script_dir="${midistar_dir}/scripts"
unix_script_dir="${script_dir}/unix"
debian_script_dir="${script_dir}/debian"
. $unix_script_dir/find_binary "release"

# If we found the binary...
if [[ $? -eq 0 ]]; then
    # Make a folder for the package
    echo Creating folders...
    package_dir="${midistar_dir}/package"
    mkdir package
    cd package
    mkdir temp

    # Add control file
    echo Adding control file...
    mkdir temp/DEBIAN
    cp "${debian_script_dir}/control" "temp/DEBIAN/."

    # Add source and binaries
    echo Adding source and binaries...
    mkdir "temp/usr"
    mkdir "temp/usr/local"
    mkdir "temp/usr/local/bin"
    cp -r "${binaries_path}" "temp/usr/local/bin/."

    # Add run script
    echo Adding run script...
    cp "${midistar_dir}/scripts/debian/run_package" "temp/usr/local/bin/midistar"

    # Create .deb
    echo Creating temp.deb...
    dpkg-deb --build temp

    # Rename
    echo Renaming to ${release_name}.deb...
    release_name=$(basename $binaries_path)
    mv "temp.deb" "${release_name}.deb"
    rm -rf temp

    cd "${midistar_dir}"
    echo Done!
fi

