#!/bin/bash

start_dir=$PWD
cd "$(dirname "$0")"
cd midistar_0.6.1

# If 'run' script doesn't exist, run setup.
# Then copy 'run' script.
if [[ ! -f "run" ]]; then
	echo "Running initial setup..."
	bash ./setup
	cp ./scripts/debian/run_release run
fi

bash ./run "$@"
cd $start_dir