#!/bin/bash

# Change to script dir
cd "$(dirname "$0")"

# Check directory
dir=${PWD##*/}
if [[ $dir == 'debian' ]]; then
    cd ../..
fi

# Find binary
. ./scripts/unix/find_binary "release"

# If we found the binary...
if [[ $? -eq 0 ]]; then
    # Set environment variables
    . ./scripts/debian/set_env "release"

    # Run executable
    exec $midistar "$@"
fi

