#!/bin/bash

start_dir=$PWD
cd "$(dirname "$0")"
cd midistar_*

# If 'run' script doesn't exist, run setup.
if [[ ! -d "run" ]]; then
	. ./setup
	cp ./scripts/debian/run_release run
fi

. ./run "$@"
cd $start_dir