#!/bin/bash

# Change to script dir
cd "$(dirname "$0")"

# Check directory
dir=${PWD##*/}
if [ $dir == 'scripts' ]; then
    echo "In 'scripts' folder. Changing to parent directory..."
    cd ..
fi

# Find binary
./scripts/find_binary

# If we found the binary...
if [ $? -eq 0 ]; then
    # Dynamic library search path hack
    export DYLD_LIBRARY_PATH="external/midifile/lib:external/rtmidi/.libs"

    # Run gdb
    exec gdb ./build/bin/midistar "$@"
fi

