#!/bin/bash

# Change to script dir
cd "$(dirname "$0")"

# Check directory
dir=${PWD##*/}
if [ $dir == 'scripts' ]; then
    cd ..
fi

# Check for 'build' folder
if [ ! -d build ]; then
    echo "'build' folder does not exist!"
    echo "Refer to BUILDING MIDISTAR in the README."
    exit
fi

# Call make
exec make -C build "$@"
