#!/bin/bash

# Change to script dir
cd "$(dirname "$0")"

# Check directory
dir=${PWD##*/}
if [ $dir == 'scripts' ]; then
    cd ..
fi

# Find binary
./scripts/find_binary "release"

# If we found the binary...
if [ $? -eq 0 ]; then
    # Set environment variables
    . ./scripts/set_env_osx "release"

    # Run executable
    exec ./build/bin/release/midistar "$@"
fi

